<a href="https://colab.research.google.com/github/cxbxmxcx/PracticalRL/blob/master/PRL_QLearning_EGreedy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import gym
import time
import random

import numpy as np

from IPython.display import clear_output


In [0]:
env = gym.make("FrozenLake-v0")

Agent Parameters

In [0]:
epsilon = 1.0
min_epsilon = 0.01
max_epsilon = 1.0
decay_rate = 0.001


alpha = 0.4  # learning rate
gamma = 0.9  # discount factor
total_steps = 10000

Initialize Q Table

In [4]:
#check out the pacman action space!
print(env.observation_space.n,env.action_space)

16 Discrete(4)


In [5]:
Q = np.ones((env.observation_space.n, env.action_space.n))
print(Q)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Selecting an Action with Exploration

In [0]:
def act(state):
  
  if np.random.uniform(0, 1) < epsilon:
    action = env.action_space.sample()
  else:
    action = np.argmax(Q[state, :])
  return action
    

Learning

In [0]:
def learn(state, state2, reward, action):
  predict = Q[state, action]
  target = reward + gamma * np.max(Q[state2, :])
  Q[state, action] = Q[state, action] + alpha * (target - predict)

Rendering the Environment

In [0]:
def render(t, env, e):
  clear_output()
  print(f'Rendering Learning Step {t}: Exploration:{e}')
  env.render()
  print(Q)
  if t < 20:
    time.sleep(2)
  elif t % 100 == 0:
    time.sleep(2)

In [9]:
learning_steps = 0
while learning_steps < total_steps:
  state = env.reset() 
  while True:
    render(learning_steps, env, epsilon)

    action = act(state)  
    state2, reward, done, info = env.step(action) 
    learn(state, state2, reward, action)
    state = state2

    learning_steps += 1
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * learning_steps) 
               
    if done:
        break
            
env.close()


Rendering Learning Step 9999: Exploration:0.010044990898875783
  (Down)
SFFF
FHFH
FFFH
HFFG
[[0.48661727 0.73779009 0.49648967 0.48901889]
 [0.53474751 0.81123625 0.5831306  0.53393839]
 [0.51291834 0.75820382 0.50996389 0.51380318]
 [0.52918147 0.5351916  0.81750411 0.51721472]
 [0.63048169 0.85977959 0.6094374  0.62605649]
 [1.         1.         1.         1.        ]
 [0.71618235 0.89717776 0.7227442  0.69353284]
 [1.         1.         1.         1.        ]
 [0.60518419 0.75125564 0.74042574 0.65430939]
 [0.73677399 0.75157265 0.80578631 0.71578659]
 [0.75882698 0.82488815 1.10490341 0.74626549]
 [1.         1.         1.         1.        ]
 [1.         1.         1.         1.        ]
 [0.78556737 0.94066485 0.80582693 0.77084301]
 [0.84134644 0.83400567 1.74771845 0.84921226]
 [1.         1.         1.         1.        ]]
